python3 main.py \
          --env_name walker_v1_add_head_reward \
          --morphologies walker \
          --expID set_noquat \
          --exp_path ../results \
          --config_path configs/3d.py \
          --gpu 1 \
          --custom_xml environments/3d_walkers \
          --actor_type set \
          --critic_type set \
          --seed 824 