python3 main.py \
          --env_name hopper \
          --morphologies hopper \
          --expID smp_forward \
          --exp_path ../results \
          --config_path configs/3d.py \
          --gpu 2 \
          --custom_xml environments/3d_hoppers/ \
          --actor_type smp \
          --critic_type smp \
          --seed 68