python3 main.py \
          --env_name cheetah \
          --morphologies cheetah \
          --expID set \
          --exp_path ../results \
          --config_path configs/3d.py \
          --gpu 3 \
          --custom_xml environments/3d_cheetahs/ \
          --actor_type set \
          --critic_type set \
          --seed 824