python3 main.py \
          --env_name  humanoid\
          --morphologies humanoid \
          --expID set3 \
          --exp_path ../results \
          --config_path configs/3d.py \
          --gpu 2 \
          --custom_xml environments/3d_humanoids \
          --actor_type set \
          --critic_type set \
          --load_buff 0 \
          --seed 824