python3 main.py \
          --env_name whh_v1_add_walker_head_reward \
          --morphologies whh \
          --expID set_hopperf \
          --exp_path ../results \
          --config_path configs/3d.py \
          --gpu 1 \
          --custom_xml environments/3d_whh \
          --actor_type set \
          --critic_type set \
          --seed 824 